CustomerID | CustomerName       | CustomerStatus | TotalCustomerMileage
-----------|--------------------|----------------|----------------------
1          | Agustine Riviera   | Silver         | 115235
2          | Alaina Sepulvida   | None           | 6008
3          | Tom Jones          | Gold           | 205767
4          | Sam Rio            | None           | 2653
5          | Jessica James      | Silver         | 127656
6          | Ana Janco          | Silver         | 136773
7          | Jennifer Cortez    | Gold           | 300582
8          | Christian Janco    | Silver         | 14642
